import pandas as pd, numpy as np
pd.set_option('display.width', 200)
df = pd.read_excel('dados -PrevencaoPerdas_Base.xlsx', sheet_name='Dados')

print("=== SHAPE / NULOS ===")
print(df.shape)
print(df.isna().sum())
print()
print("=== DTYPES ===")
print(df.dtypes)
print()
print("=== DESFECHO ===")
print(df.desfecho.value_counts())
print((df.desfecho.value_counts(normalize=True)*100).round(2))
print()
for c in ['filial','regiao','pacote_tipo','faixa_caucao','sexo','faixa_idade','parou_48h','sem_ping_24h','violacao_blindagem','dist_base_km','device_compartilhado','jornada_impossivel']:
    print(f"--- {c}")
    print(df[c].value_counts(dropna=False).to_string())
    print()
print("=== NUMERICAS ===")
print(df[['dias_locacao','dias_inadimplencia_max','dia_primeiro_sinal','dia_desfecho']].describe().round(2).to_string())
