import pandas as pd, numpy as np
pd.set_option('display.width',250)
df = pd.read_excel('dados -PrevencaoPerdas_Base.xlsx', sheet_name='Dados')
bin_cols=['parou_48h','sem_ping_24h','violacao_blindagem','device_compartilhado','jornada_impossivel']
for c in bin_cols: df[c+'_b']=(df[c]=='SIM').astype(int)
df['n_sin']=df[[c+'_b' for c in bin_cols]].sum(axis=1)
df['tem_sinal']=df.dia_primeiro_sinal.notna()

print("### 1. Duplicatas")
print("locacao_id duplicados:", df.locacao_id.duplicated().sum())
print("linhas totalmente duplicadas:", df.drop(columns=['locacao_id']).duplicated().sum())
print()
print("### 2. Coerencia temporal")
print("dia_primeiro_sinal > dia_desfecho:", (df.dia_primeiro_sinal > df.dia_desfecho).sum())
print("dia_primeiro_sinal > dias_locacao:", (df.dia_primeiro_sinal > df.dias_locacao).sum())
print("dia_desfecho > dias_locacao:", (df.dia_desfecho > df.dias_locacao).sum())
print("dia_desfecho <= 0:", (df.dia_desfecho<=0).sum())
print()
print("### 3. Sinal de telemetria SEM data de primeiro sinal")
inc = df[(df.n_sin>0) & (~df.tem_sinal)]
print("qtd:", len(inc))
print(inc.groupby('desfecho').size())
print(inc[[c+'_b' for c in bin_cols]].sum())
print("inadimplencia_max desses:", inc.dias_inadimplencia_max.describe().round(1).to_dict())
print()
print("### 4. Data de primeiro sinal SEM nenhum sinal de telemetria nem inadimplencia")
inc2 = df[(df.n_sin==0)&(df.dias_inadimplencia_max==0)&(df.tem_sinal)]
print("qtd:", len(inc2))
print()
print("### 5. Qual limiar de inadimplencia 'liga' o sinal? (casos sem telemetria)")
sub=df[df.n_sin==0].copy()
sub['fx']=pd.cut(sub.dias_inadimplencia_max,[-1,0,4,6,7,9,14,21,50])
print(pd.crosstab(sub.fx, sub.tem_sinal))
print()
print("### 6. inadimplencia por desfecho")
print(df.groupby('desfecho').dias_inadimplencia_max.describe().round(1).to_string())
print()
print("### 7. APROPRIADA sem nenhum sinal")
print(df[(df.desfecho=='APROPRIADA')&(~df.tem_sinal)].to_string())
print()
print("### 8. DEVOLVIDA com gap>0 (terminou antes do contrato)")
print(df[(df.desfecho=='DEVOLVIDA')&(df.dias_locacao!=df.dia_desfecho)][['locacao_id','dias_locacao','dia_desfecho','dias_inadimplencia_max','dia_primeiro_sinal']].to_string())
print()
print("### 9. RECUPERADA/APROPRIADA sem sinal antes do desfecho")
bad = df[(df.desfecho!='DEVOLVIDA')&(df.tem_sinal)&(df.dia_primeiro_sinal>=df.dia_desfecho)]
print("qtd sinal no mesmo dia ou depois do desfecho:", len(bad))
print(bad[['locacao_id','desfecho','dia_primeiro_sinal','dia_desfecho']].head(10).to_string())
